############### GET ALL ITEMS #################
get http://simrest.loc/api/user

############### GET SINGLE ITEM #################
get http://simrest.loc/api/user/1

############### POST ################
post http://simrest.loc/api/user HTTP/1.1
Content-Type: application/json

{
    "name":"After Dark", 
    "phone":"+94837493848"
}

############## PUT #################
put http://simrest.loc/api/user/1 HTTP/1.1
Content-Type: application/json

{
    "name":"Scorpions",
    "phone":"+74837493848"
}

############## DELETE #################
delete http://simrest.loc/api/user/2 HTTP/1.1
Content-Type: application/json




