############### GET TOKEN #################
get http://simrest.loc/api/access?phone=74837493848&name=Scorpions

############### GET ALL ITEMS #################
get http://simrest.loc/api/user

{
    "token":"84754jd8u5jd9"
}

############### GET SINGLE ITEM #################
get http://simrest.loc/api/user/1

{
    "token":"84754jd8u5jd9"
}

############### POST ################
post http://simrest.loc/api/user HTTP/1.1
Content-Type: application/json

{
    "name":"Bananarama", 
    "phone":"+74837493848"
}

############## PUT #################
put http://simrest.loc/api/user/1 HTTP/1.1
Content-Type: application/json

{
    "name":"Scorpions",
    "phone":"+74837493848"
}

############## DELETE #################
delete http://simrest.loc/api/user/2 HTTP/1.1
Content-Type: application/json




