############### GET TOKEN ввести 11 цифр, без знака + #################
get http://simrest.loc/api/access/?phone=74837493848

############### GET ALL ITEMS #################
get http://simrest.loc/api/user

{
    "token":"wtEhHBvf4Hcxw"
}

############### GET SINGLE ITEM #################
get http://simrest.loc/api/user/6

{
    "token":"wtEhHBvf4Hcxw"
}

############### POST ################
post http://simrest.loc/api/user HTTP/1.1
Content-Type: application/json

{
    "token":"wtEhHBvf4Hcxw",
    "name":"Testing post", 
    "phone":"+74837493840"
}

############## PUT #################
put http://simrest.loc/api/user/9 HTTP/1.1
Content-Type: application/json

{
    "token":"wtEhHBvf4Hcxw",
    "name":"Tiber septin",
    "phone":"+74837493848"
}

############## DELETE #################
delete http://simrest.loc/api/user/9 HTTP/1.1
Content-Type: application/json

{
    "token":"wtEhHBvf4Hcxw"
}




